# Introduction to NumPy

## What is NumPy?
[NumPy](https://numpy.org/doc/) (Numerical Python) is a Python library for efficient numerical computing, particularly in scientific applications.

### Key Features:
- Provides the **ndarray** data structure for homogeneous, multidimensional arrays
- Optimized for handling large datasets
- Offers comprehensive mathematical functions
- Enables vectorized operations for improved performance

## Table of Contents
1. [Importing NumPy](#Importing-NumPy)
2. [NumPy Data Types](#NumPy-Data-Types)
3. [Creating Arrays](#Creating-Arrays)
4. [Array Attributes](#Array-Attributes)
5. [Array Operations](#Array-Operations)
6. [Indexing and Slicing](#Indexing-and-Slicing)
7. [Array Manipulation](#Array-Manipulation)
8. [Linear Algebra](#Linear-Algebra)
9. [Random Sampling](#Random-Sampling)
10. [Statistics](#Statistics)

## Importing NumPy

In [1]:
import numpy as np

In [2]:
# Check versions
import platform
print('Python version:', platform.python_version())
print('NumPy version:', np.__version__)

Python version: 3.13.3
NumPy version: 2.2.5


## NumPy Data Types
NumPy supports more data types than Python, including:
- Integer types: `int8`, `int16`, `int32`, `int64`
- Unsigned integers: `uint8`, `uint16`, `uint32`, `uint64`
- Floating point: `float16`, `float32`, `float64`
- Complex numbers: `complex64`, `complex128`
- Boolean: `bool_`
- Others: `string_`, `unicode_`, `object_`

## Creating Arrays

### From Python lists/tuples

In [3]:
# 1D array
arr1 = np.array([1, 2, 3])
print(arr1)

[1 2 3]


In [4]:
# 2D array (matrix)
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [5]:
# With specific data type
arr_float = np.array([1, 2, 3], dtype=np.float32)
print(arr_float)

[1. 2. 3.]


### Special array creation functions

In [6]:
# Sequence with step
print(np.arange(0, 10, 2))  # start, stop, step

[0 2 4 6 8]


In [7]:
# Linearly spaced values
print(np.linspace(0, 1, 5))  # start, stop, num_points

[0.   0.25 0.5  0.75 1.  ]


In [8]:
# Zeros array
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Ones array
print(np.ones((2, 2), dtype=int))

[[1 1]
 [1 1]]


In [10]:
# Identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Random values
np.random.seed(42)  # For reproducibility
print(np.random.rand(3, 3))  # Uniform distribution [0,1)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


## Array Attributes

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:", arr)
print("Shape:", arr.shape)  # Dimensions
print("Number of dimensions:", arr.ndim)
print("Size (total elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (bytes):", arr.itemsize)
print("Total memory size (bytes):", arr.nbytes)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (total elements): 6
Data type: int64
Item size (bytes): 8
Total memory size (bytes): 48


## Array Operations

### Element-wise operations

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", b / a)
print("Exponentiation:", a ** 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Exponentiation: [1 4 9]


### Broadcasting

In [14]:
# Scalar to array
print(a + 5)

# Different shaped arrays
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])
print(matrix + vector)

[6 7 8]
[[11 22 33]
 [14 25 36]]


### Universal functions (ufuncs)

In [15]:
print("Square root:", np.sqrt(a))
print("Exponential:", np.exp(a))
print("Natural log:", np.log(a))
print("Base 10 log:", np.log10(a))
print("Trig functions:", np.sin(a))

Square root: [1.         1.41421356 1.73205081]
Exponential: [ 2.71828183  7.3890561  20.08553692]
Natural log: [0.         0.69314718 1.09861229]
Base 10 log: [0.         0.30103    0.47712125]
Trig functions: [0.84147098 0.90929743 0.14112001]


## Indexing and Slicing

### Basic indexing

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at [1,2]:", arr[1, 2])
print("First row:", arr[0])
print("Last column:", arr[:, -1])

Element at [1,2]: 6
First row: [1 2 3]
Last column: [3 6 9]


### Slicing

In [17]:
print("Submatrix:", arr[1:, :2])  # Rows 1+, columns 0-1

Submatrix: [[4 5]
 [7 8]]


### Boolean indexing

In [18]:
print("Elements > 5:", arr[arr > 5])

Elements > 5: [6 7 8 9]


## Array Manipulation

### Reshaping

In [19]:
print("Reshaped:", arr.reshape(9))  # Flatten
print("Reshaped with -1:", arr.reshape(3, -1))  # Automatic dimension

Reshaped: [1 2 3 4 5 6 7 8 9]
Reshaped with -1: [[1 2 3]
 [4 5 6]
 [7 8 9]]


### Concatenation

In [20]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print("Vertical stack:", np.vstack((a, b)))
print("Horizontal stack:", np.hstack((a, b.T)))

Vertical stack: [[1 2]
 [3 4]
 [5 6]]
Horizontal stack: [[1 2 5]
 [3 4 6]]


### Transpose

In [21]:
print("Transpose:", arr.T)

Transpose: [[1 4 7]
 [2 5 8]
 [3 6 9]]


### Copies vs Views

In [22]:
view = arr.view()  # Shares memory
copy = arr.copy()  # New memory

print("Shares memory:", np.shares_memory(arr, view))
print("Shares memory:", np.shares_memory(arr, copy))

Shares memory: True
Shares memory: False


## Linear Algebra

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix multiplication:", A @ B)  # or np.dot(A, B)
print("Element-wise multiplication:", A * B)
print("Determinant:", np.linalg.det(A))
print("Inverse:", np.linalg.inv(A))

Matrix multiplication: [[19 22]
 [43 50]]
Element-wise multiplication: [[ 5 12]
 [21 32]]
Determinant: -2.0000000000000004
Inverse: [[-2.   1. ]
 [ 1.5 -0.5]]


## Random Sampling

In [24]:
print("Random integers:", np.random.randint(0, 10, 5))
print("Normal distribution:", np.random.normal(0, 1, 5))
print("Shuffled array:", np.random.permutation([1, 2, 3, 4, 5]))

Random integers: [7 2 5 4 1]
Normal distribution: [ 0.23309524  0.11799461  1.46237812  1.53871497 -2.43910582]
Shuffled array: [1 2 3 5 4]


## Statistics

In [25]:
data = np.array([[1, 2, 3], [4, 5, 6]])

print("Mean:", np.mean(data))
print("Column means:", np.mean(data, axis=0))
print("Row means:", np.mean(data, axis=1))
print("Standard deviation:", np.std(data))
print("Median:", np.median(data))
print("Min/Max:", np.min(data), np.max(data))

Mean: 3.5
Column means: [2.5 3.5 4.5]
Row means: [2. 5.]
Standard deviation: 1.707825127659933
Median: 3.5
Min/Max: 1 6
