# Workshop 7: Confitioning


# Exercise 1
- Build the Vandermonde matrix A, generated by the vector x=[1.0,2.0,...,6.0] using the np.vander(x, increasing=True) function from numpy. 
- Calculate its condition number in infinite norm without using the cond function from numpy.linalg and then compare its value with that obtained using the function.
- Consider the linear system Ax=b with coefficient matrix A and right-hand side constructed so that the exact solution is the vector x=[1,1,1,1,1,1] (each of its components is 1) and solve it using the solve method of the linalg module of Scipy.
- perturb the vector of the right-hand side by the amount

$$
\delta b = 0.025 \, \ast \,
\left [
\begin{array}{c}
1\\
0\\
0\\
0
\end{array}
\right ]
$$
- Solve the system with perturbed right-hand side $b + \delta b$ ((using the solve method of the linalg module of Scipy).
- Calculate the relative error on the right-hand side and the relative error on the solution. What can be concluded?

N.B. for the calculation of the inverse of the matrix A use the function of numpy.linalg.inv(A).


In [1]:
import numpy as np
import numpy.linalg as npl
import scipy.linalg as spl
import matplotlib.pyplot as plt
import functions

In [2]:
x = np.arange(1.0, 7.0)
A = np.vander(x, increasing=True)

print(A)


def norma_inf(A):
    return np.max(np.sum(np.abs(A), axis=1))


mycond = norma_inf(A) * norma_inf(np.linalg.inv(A))
print("Conditioning in infinite norm {:e}".format(mycond))
condp = np.linalg.cond(A, np.inf)
print("Conditioning in infinite norm with numpy {:e}".format(condp))

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01 2.430e+02]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02 1.024e+03]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02 3.125e+03]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03 7.776e+03]]
Conditioning in infinite norm 1.204321e+06
Conditioning in infinite norm with numpy 1.204321e+06


In [3]:
b = np.sum(A, axis=1).reshape(6, 1)
print(b)

bp = b.copy()

bp[0] = b[0] + 0.025
er = np.linalg.norm(bp - b, np.inf) / np.linalg.norm(b, np.inf)
print("error ", er)

[[6.000e+00]
 [6.300e+01]
 [3.640e+02]
 [1.365e+03]
 [3.906e+03]
 [9.331e+03]]
error  2.679241238881187e-06


In [4]:
xe = np.ones((6, 1))
xp = spl.solve(A, bp)
print("Exact solution of the system without perturbation \n ", xe)
print("Solution of the system with perturbed right-hand side\n ", xp)
er = np.linalg.norm(xp - xe, np.inf) / np.linalg.norm(xe, np.inf)
print("solution error ", er)

Exact solution of the system without perturbation 
  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Solution of the system with perturbed right-hand side
  [[1.15      ]
 [0.7825    ]
 [1.12083333]
 [0.96770833]
 [1.00416667]
 [0.99979167]]
solution error  0.21749999998492908


## Exercise 2
Given the linear system $Ax = b$, with
$$
A =
\left [
\begin{array}{ccc}
6 & 63 & 662.2\\
63 & 662.2 & 6967.8\\
662.2 & 6967.8 & 73393.5664
\end{array}
\right ], \qquad
b =
\left [
\begin{array}{c}
1.1\\
2.33\\
1.7
\end{array}
\right ]
$$
- find the solution vector $x$ (using the solve method of the linalg module of Scipy);
- perturb the coefficient matrix by the amount
$$
\delta A =
0.01 \, \ast \,
\left [ \begin{array}{ccc}
1 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{array}
\right ]
$$
then calculate the relative error on the solution and compare it with the relative perturbation on the input data. What do you observe?

In [5]:
A = np.array([[6, 63, 662.2], [63, 662.2, 6967.8], [662.2, 6967.8, 73393.5664]])
b = np.array([1.1, 2.33, 1.7])

KA = npl.cond(A, np.inf)
print("Condition number of A {:e}".format(KA))
x = spl.solve(A, b)

A1 = A.copy()
A1[0, 0] = A[0, 0] + 0.01
xp = spl.solve(A1, b)

er = npl.norm(A - A1, np.inf) / npl.norm(A, np.inf)
print("Relative error on the data ", er)
print("Relative error on the data  in percentage ", er * 100, "%")

ers = npl.norm(xp - x, np.inf) / npl.norm(x, np.inf)
print("Relative error on the solution ", ers)
print("Relative error on the solution  in percentage ", ers * 100, "%")

Condition number of A 1.975302e+10
Relative error on the data  1.2342088165597937e-07
Relative error on the data  in percentage  1.2342088165597937e-05 %
Relative error on the solution  0.9995081547933587
Relative error on the solution  in percentage  99.95081547933587 %


## Exercise 3
 
Given the linear system $Ax = b$, with $A$ being the Hilbert matrix of order
$4$ and $b = [1, 1, 1, 1]^T$,
 - find the solution vector $x$ (using the solve method of the linalg module of Scipy);
 -  perturb the vector of the right-hand side by the amount
$$
\delta b = 0.01 \, \ast \,
\left [
\begin{array}{c}
1\\
-1\\
1\\
-1
\end{array}
\right ]
$$
then calculate the solution of the system $A x_p= b_p$ with the perturbed right-hand side $b_p=b+ \delta b$.
Calculate the relative error on the solution and compare it with the relative perturbation on the input data. What do you observe?

Note: for constructing the Hilbert matrix use the hilbert(n) function from scipy.linalg
(scipy.linalg.hilbert(n))  where you need to specify the order n of the matrix.

In [6]:
n = 4
A = spl.hilbert(4)
print(A)
condA = np.linalg.cond(A, np.inf)
print("Indice di condizionamento di A {:e}".format(condA))

b = np.array([1, 1, 1, 1])

x = spl.solve(A, b)


db = np.array([0.01, -0.01, 0.01, -0.01])
bp = b + db

xp = spl.solve(A, bp)

er = npl.norm(db, 2) / npl.norm(b, 2)
print("Errore relativo sui dati ", er)
print("Errore relativo sui dati  in percentuale", er * 100, "%")

ers = npl.norm(x - xp, np.inf) / npl.norm(x, np.inf)
print("Errore relativo sulla soluzione", ers)
print("Errore relativo sulla soluzione  in percentuale", ers * 100, "%")

[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
Indice di condizionamento di A 2.837500e+04
Errore relativo sui dati  0.01
Errore relativo sui dati  in percentuale 1.0 %
Errore relativo sulla soluzione 0.7566666666666878
Errore relativo sulla soluzione  in percentuale 75.66666666666877 %


## Direct methods for the numerical solution of a linear system

## Note 1.
The function *scipy.linalg.lu(A)*  , given an input matrix A of full rank, returns the matrices $P^T$,L,U,  of the LU factorization of matrix A such that PA=LU (it returns the transposed permutation matrix)

In [7]:
import numpy as np
import scipy as sp
from scipy.linalg import lu

A = np.array([[2, 1], [3, 4]])
PT, L, U = lu(A)  # Returns the transposed permutation matrix in output
P = PT.copy()  # P is the permutation matrix
print("A=", A)
print("L=", L)
print("U=", U)
print("P=", P)
# LU is the factorization of P*A (theorem 2)
A1 = P @ A  # equivalent to matrix x matrix product np.dot(P,A)
A1Fatt = L @ U  # equivalent to np.dot(L,U)
print("Matrix P*A \n", A1)
print("Matrix obtained by multiplying L and U \n", A1Fatt)

A= [[2 1]
 [3 4]]
L= [[1.         0.        ]
 [0.66666667 1.        ]]
U= [[ 3.          4.        ]
 [ 0.         -1.66666667]]
P= [[0. 1.]
 [1. 0.]]
Matrix P*A 
 [[3. 4.]
 [2. 1.]]
Matrix obtained by multiplying L and U 
 [[3. 4.]
 [2. 1.]]


## Note 2
The function *scipy.linalg.cholesky(a, lower=True)*, given an input symmetric and positive definite matrix, returns the lower triangular matrix L such that $A=L \cdot L^T$. If the input matrix is not positive definite, it returns an error.

In [8]:
from scipy.linalg import cholesky

A = np.array([[2, 1, 3], [1, 5, 7], [3, 7, 12]])
print(A)

[[ 2  1  3]
 [ 1  5  7]
 [ 3  7 12]]


In [9]:
L = cholesky(A, lower=True)
print(L)
A1 = L @ L.T
print("A1=\n", A1)

[[1.41421356 0.         0.        ]
 [0.70710678 2.12132034 0.        ]
 [2.12132034 2.59272486 0.8819171 ]]
A1=
 [[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Note 3
The function *scipy.linalg.qr(a)*, given an input matrix A (nxn)  of full rank, returns the matrices Q (orthogonal of dimension nxn) and R (nxn) upper triangular such that $A=Q \cdot R$

In [10]:
from scipy.linalg import qr

A = np.array([[2, 1, 3], [1, 5, 7], [3, 7, 12]])
Q, R = qr(A)
print("Q=", Q)
print("R=", R)
A1 = Q @ R
print(A1)

Q= [[-0.53452248  0.6882472  -0.49051147]
 [-0.26726124 -0.6882472  -0.67445327]
 [-0.80178373 -0.22941573  0.55182541]]
R= [[ -3.74165739  -7.48331477 -13.09580085]
 [  0.          -4.35889894  -5.50597761]
 [  0.           0.           0.42919754]]
[[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Exercise 4
- implement a function LUsolve(P,A,L,U,b) that solves the linear system Ax=b in the case of $PA = LU$ factorization,
combining the forward and backward solving methods implemented in the SolveTriangular.py file.
- test it on the matrix A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]]) with the right-hand side chosen so that the exact solution of the linear system is the vector of all 1s.

In [11]:
def LUsolve(P, A, L, U, b):
    pb = np.dot(P, b)
    y, flag = functions.Lsolve(L, pb)
    if flag == 0:
        x, flag = functions.Usolve(U, y)
    else:
        return [], flag

    return x, flag

In [12]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
print("A=", A)
b = np.sum(A, axis=1).reshape(4, 1)
print("b=", b)
PT, L, U = lu(A)
P = PT.T.copy()
print("P= \n", P)
print("L=\n", L)
print("U=\n", U)
# The row permutations made on the matrix are also applied to the right-hand side
x, flag = LUsolve(P, A, L, U, b)
print("flag= \n", flag, "\n x= \n", x)

A= [[2 5 8 7]
 [5 2 2 8]
 [7 5 6 6]
 [5 4 4 8]]
b= [[22]
 [17]
 [24]
 [21]]
P= 
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
L=
 [[ 1.          0.          0.          0.        ]
 [ 0.28571429  1.          0.          0.        ]
 [ 0.71428571  0.12        1.          0.        ]
 [ 0.71428571 -0.44       -0.46153846  1.        ]]
U=
 [[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]]
flag= 
 1 
 x= 
 [[1.]
 [1.]
 [1.]
 [1.]]


## Exercise 5
Implement a function *solve_nsis(A,B)* to compute the solution of a general linear system $AX = B$, with $X, B$ matrices, that uses the LU factorization of the matrix PA, to solve n linear systems: having the same coefficient matrix A and right-hand side the i-th column of the matrix B. 
Then use it to calculate the inverse of the
non-singular matrices
$$
A=\left[
\begin{array}{ccc}
3 & 5 & 7\\
2 & 3 & 4\\
5 & 9 & 11
\end{array}
\right ], \qquad
A=\left[
\begin{array}{cccc}
1 & 2 & 3 & 4\\
2 & -4 & 6 & 8\\
-1 & -2 & -3 & -1\\
5 & 7 & 0 & 1
\end{array}
\right ],
$$
comparing the results obtained with the output
of the *scipy.linalg.inv(A)*

In [13]:
def solve_nsis(A, B):
    m, n = A.shape
    flag = 0
    if n != m:
        print("Non-square matrix")
        return

    X = np.zeros((n, n))
    PT, L, U = lu(A)
    P = PT.T.copy()
    if flag == 0:
        for i in range(n):
            y, flag = functions.Lsolve(L, P @ B[:, i])
            x, flag = functions.Usolve(U, y)
            X[:, i] = x.reshape(
                n,
            )
    else:
        print("Zero diagonal element")
        X = []

    return X

In [14]:
A1 = np.array([[3, 5, 7], [2, 3, 4], [5, 9, 11]])
m, n = A1.shape
B = np.eye(m)
X = solve_nsis(A1, B)
print("my inversa \n", X)
print("Inversa con linalg \n ", np.linalg.inv(A1))

A2 = np.array([[1, 2, 3, 4], [2, -4, 6, 8], [-1, -2, -3, -1], [5, 7, 0, 1]])
m, n = A2.shape
B = np.eye(m)
X = solve_nsis(A2, B)
print("my inversa \n", X)
print("Inversa con linalg \n ", np.linalg.inv(A2))

my inversa 
 [[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
Inversa con linalg 
  [[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
my inversa 
 [[-4.16666667e-01  1.75000000e-01 -6.66666667e-02  2.00000000e-01]
 [ 2.50000000e-01 -1.25000000e-01  6.53072367e-17 -8.16340459e-18]
 [-1.38888889e-01  2.50000000e-02 -4.22222222e-01 -6.66666667e-02]
 [ 3.33333333e-01  4.62592927e-18  3.33333333e-01 -9.25185854e-18]]
Inversa con linalg 
  [[-4.16666667e-01  1.75000000e-01 -6.66666667e-02  2.00000000e-01]
 [ 2.50000000e-01 -1.25000000e-01 -4.89804276e-17 -4.08170230e-18]
 [-1.38888889e-01  2.50000000e-02 -4.22222222e-01 -6.66666667e-02]
 [ 3.33333333e-01  3.26536184e-18  3.33333333e-01 -8.70763157e-18]]


## Exercise 6
Using the PA=LU factorization of one of the matrices from the previous point, compute its determinant.


In [15]:
PT, L1, U1 = lu(A2)
P = PT.copy()

det = np.prod(np.diag(U1)) * np.linalg.det(P)

print("my det: ", det)
print("Numpy det:", np.linalg.det(A2))

my det:  -359.99999999999994
Numpy det: -360.00000000000006
