## Workshop 8: Confitioning


# Esercizio 1
- Costruire la matrice di Vandermonde A, generata dal vettore x=[1.0,2.0,...,6.0] utilizzando la funzione np.vander(x, increasing=True) di numpy. 
- Calcolarne l'indice di condizionamento in norma infinito senza utilizzare la funzione cond di numpy.linalg e poi confrontarne il valore con quello ottenuto utilizzando la funzione.
- Considerare il sistema lineare Ax=b  con matrice dei coefficienti A e termine noto costruito in maniera tale che la soluzione esatta sia il vettore x=[1,1,1,1,1,1] (ogni sua componente è 1) e risolverlo usando il metodo solve del modulo linalg di Scipy.
- perturbare il vettore dei termini noti della quantità

$$
\delta b = 0.025 \, \ast \,
\left [
\begin{array}{c}
1\\
0\\
0\\
0
\end{array}
\right ]
$$
- Risolvere il sistema con termine noto pertubato $b + \delta b$ ((usando il metodo solve del modulo linalg di Scipy).
- Calcolare l'errore relativo sul termine noto e l'errore relativo sulla soluzione. Cosa si può concludere?

N.B. per il calcolo dell'inversa della matrice di A usare la funzione di numpy.linalg.inv(A).


In [ ]:
import numpy as np
import numpy.linalg as npl
import scipy.linalg as spl
import matplotlib.pyplot as plt
import functions

In [2]:
x = np.arange(1.0, 7.0)
A = np.vander(x, increasing=True)

print(A)


def norma_inf(A):
    return np.max(np.sum(np.abs(A), axis=1))


mycond = norma_inf(A) * norma_inf(np.linalg.inv(A))
print("condizionamento in norma infinito {:e}".format(mycond))
condp = np.linalg.cond(A, np.inf)
print("condizionamento in norma infinito con numpy {:e}".format(condp))

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01 2.430e+02]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02 1.024e+03]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02 3.125e+03]
 [1.000e+00 6.000e+00 3.600e+01 2.160e+02 1.296e+03 7.776e+03]]
condizionamento in norma infinito 1.204321e+06
condizionamento in norma infinito con numpy 1.204321e+06


In [3]:
b = np.sum(A, axis=1).reshape(6, 1)
print(b)

bp = b.copy()

bp[0] = b[0] + 0.025
er = np.linalg.norm(bp - b, np.inf) / np.linalg.norm(b, np.inf)
print("errore ", er)

[[6.000e+00]
 [6.300e+01]
 [3.640e+02]
 [1.365e+03]
 [3.906e+03]
 [9.331e+03]]
errore  2.679241238881187e-06


In [4]:
xe = np.ones((6, 1))
xp = spl.solve(A, bp)
print("Soluzione esatta sistema senza perturbazione \n ", xe)
print("Soluzione sistema con termine noto perturbato\n ", xp)
er = np.linalg.norm(xp - xe, np.inf) / np.linalg.norm(xe, np.inf)
print("errore soluzione ", er)

Soluzione esatta sistema senza perturbazione 
  [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Soluzione sistema con termine noto perturbato
  [[1.15      ]
 [0.7825    ]
 [1.12083333]
 [0.96770833]
 [1.00416667]
 [0.99979167]]
errore soluzione  0.21749999998492908


## Esercizio 2
Assegnato il sistema lineare $Ax = b$, con
$$
A =
\left [
\begin{array}{ccc}
6 & 63 & 662.2\\
63 & 662.2 & 6967.8\\
662.2 & 6967.8 & 73393.5664
\end{array}
\right ], \qquad
b =
\left [
\begin{array}{c}
1.1\\
2.33\\
1.7
\end{array}
\right ]
$$
- trovare il vettore soluzione $x$ (usando il metodo solve del modulo linalg di Scipy);
- perturbare la matrice dei coefficienti della quantità
$$
\delta A =
0.01 \, \ast \,
\left [ \begin{array}{ccc}
1 & 0 & 0\\
0 & 0 & 0\\
0 & 0 & 0
\end{array}
\right ]
$$
quindi calcolare l'errore relativo sulla soluzione e confrontarlo con la
perturbazione relativa sui dati di ingresso. Cosa si osserva?

In [5]:
A = np.array([[6, 63, 662.2], [63, 662.2, 6967.8], [662.2, 6967.8, 73393.5664]])
b = np.array([1.1, 2.33, 1.7])

KA = npl.cond(A, np.inf)
print("Indice di condizionamento di A {:e}".format(KA))
x = spl.solve(A, b)

A1 = A.copy()
A1[0, 0] = A[0, 0] + 0.01
xp = spl.solve(A1, b)

er = npl.norm(A - A1, np.inf) / npl.norm(A, np.inf)
print("Errore relativo sui dati ", er)
print("Errore relativo sui dati  in percentuale ", er * 100, "%")

ers = npl.norm(xp - x, np.inf) / npl.norm(x, np.inf)
print("Errore relativo sulla soluzione ", ers)
print("Errore relativo sulla soluzione  in percentuale ", ers * 100, "%")

Indice di condizionamento di A 1.975302e+10
Errore relativo sui dati  1.2342088165597937e-07
Errore relativo sui dati  in percentuale  1.2342088165597937e-05 %
Errore relativo sulla soluzione  0.9995081547933587
Errore relativo sulla soluzione  in percentuale  99.95081547933587 %


## Esercizio 3
 
Assegnato il sistema lineare $Ax = b$, con $A$ matrice di Hilbert di ordine
$4$ e $b = [1, 1, 1, 1]^T$,
 - trovare il vettore soluzione $x$ (usando il metodo solve del modulo linalg di Scipy);
 -  perturbare il vettore dei termini noti della quantità
$$
\delta b = 0.01 \, \ast \,
\left [
\begin{array}{c}
1\\
-1\\
1\\
-1
\end{array}
\right ]
$$
quindi calcolare la soluzione del sistema $A x_p= b_p$ con termine noto $b_p=b+ \delta b$.
Calcolare l'errore relativo sulla soluzione e confrontarlo con la perturbazione relativa sui dati di ingresso. Cosa si osserva?

Nota: per la costruzione della matrice di Hilbert usare la funzione hilbert(n) del modulo scipy.linalg
(scipy.linalg.hilbert(n))  dove bisogna specificare l'ordine n della matrice.

## Metodi diretti per la soluzione numerica di un sistema lineare

## Nota 1.
La funzione *scipy.linalg.lu(A)*  , presa in input una matrice A a rango massimo, restituisce in output le matrici $P^T$,L,U,  della fattorizzazione di LU della matrice A in maniera tale che PA=LU (restituisce la matrice di permutazione trasposta)

In [6]:
import numpy as np
import scipy as sp
from scipy.linalg import lu

A = np.array([[2, 1], [3, 4]])
PT, L, U = lu(A)  # Restituisce in output la trasposta della matrice di Permutazione
P = PT.copy()  # P è la matrice di permutazione
print("A=", A)
print("L=", L)
print("U=", U)
print("P=", P)
# LU è la fattorizzazione di P*A (terorema 2)
A1 = P @ A  # equivale al prodotto matrice x matrice np.dot(P,A)
A1Fatt = L @ U  # equivale a np.dot(L,U)
print("Matrice P*A \n", A1)
print("Matrice ottenuta moltipicando Le ed U \n", A1Fatt)

A= [[2 1]
 [3 4]]
L= [[1.         0.        ]
 [0.66666667 1.        ]]
U= [[ 3.          4.        ]
 [ 0.         -1.66666667]]
P= [[0. 1.]
 [1. 0.]]
Matrice P*A 
 [[3. 4.]
 [2. 1.]]
Matrice ottenuta moltipicando Le ed U 
 [[3. 4.]
 [2. 1.]]


## Nota 2
La funzione *scipy.linalg.cholesky(a, lower=True)*, presa in input una matrice simmetrica e definta positiva restituisce in output la matrice L triangolare inferiore tale che $A=L \cdot L^T$. Se la matrice in input non è definita positiva, restituisce un errore.

In [7]:
from scipy.linalg import cholesky

A = np.array([[2, 1, 3], [1, 5, 7], [3, 7, 12]])
print(A)

[[ 2  1  3]
 [ 1  5  7]
 [ 3  7 12]]


In [8]:
L = cholesky(A, lower=True)
print(L)
A1 = L @ L.T
print("A1=\n", A1)

[[1.41421356 0.         0.        ]
 [0.70710678 2.12132034 0.        ]
 [2.12132034 2.59272486 0.8819171 ]]
A1=
 [[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Nota 3
La funzione *scipy.linalg.qr(a)*, presa in input una matrice A (nxn)  a rango massimo, restituisce in output le matrici Q (ortogonale di dimensione nxn) ed una matrice R (nxn) triangolare superiore tale che $A=Q \cdot R$

In [9]:
from scipy.linalg import qr

A = np.array([[2, 1, 3], [1, 5, 7], [3, 7, 12]])
Q, R = qr(A)
print("Q=", Q)
print("R=", R)
A1 = Q @ R
print(A1)

Q= [[-0.53452248  0.6882472  -0.49051147]
 [-0.26726124 -0.6882472  -0.67445327]
 [-0.80178373 -0.22941573  0.55182541]]
R= [[ -3.74165739  -7.48331477 -13.09580085]
 [  0.          -4.35889894  -5.50597761]
 [  0.           0.           0.42919754]]
[[ 2.  1.  3.]
 [ 1.  5.  7.]
 [ 3.  7. 12.]]


## Esercizio 4
- si implementi una function LUsolve(P,A,L,U,b) che risolve il sistema lineare Ax=b nel caso di fattorizzazione $PA = LU$ assegnata,
combinando i metodi di risoluzione in avanti ed all'indietro  implementati nel file SolveTriangular.py.
- si testi sulla matrice A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]]) con termine noto b scelto in maniera tale che la soluzione esatta del sistema lineare sia il vettore formato da tutti 1.

In [ ]:
def LUsolve(P, A, L, U, b):
    pb = np.dot(P, b)
    y, flag = functions.Lsolve(L, pb)
    if flag == 0:
        x, flag = functions.Usolve(U, y)
    else:
        return [], flag

    return x, flag

In [ ]:
import numpy as np
from scipy.linalg import lu

A = np.array([[2, 5, 8, 7], [5, 2, 2, 8], [7, 5, 6, 6], [5, 4, 4, 8]])
print("A=", A)
b = np.sum(A, axis=1).reshape(4, 1)
print("b=", b)
PT, L, U = lu(A)
P = PT.T.copy()
print("P= \n", P)
print("L=\n", L)
print("U=\n", U)
# Le permutazioni di righe fatte sulla matrice vengono effettuate anche sul termine noto
x, flag = LUsolve(P, A, L, U, b)
print("flag= \n", flag, "\n x= \n", x)

A= [[2 5 8 7]
 [5 2 2 8]
 [7 5 6 6]
 [5 4 4 8]]
b= [[22]
 [17]
 [24]
 [21]]
P= 
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]
L=
 [[ 1.          0.          0.          0.        ]
 [ 0.28571429  1.          0.          0.        ]
 [ 0.71428571  0.12        1.          0.        ]
 [ 0.71428571 -0.44       -0.46153846  1.        ]]
U=
 [[ 7.          5.          6.          6.        ]
 [ 0.          3.57142857  6.28571429  5.28571429]
 [ 0.          0.         -1.04        3.08      ]
 [ 0.          0.          0.          7.46153846]]
flag= 
 1 
 x= 
 [[1.]
 [1.]
 [1.]
 [1.]]


## Esercizio 5
Si implementi una function *solve_nsis(A,B)* per il calcolo della soluzione di un generale sistema lineare $AX = B$, con $X, B$ matrici, che usi la fattorizzazione LU della matrice PA, per risolvere n sistemi lineari: aventi la stessa matrice dei coefficienti A e termine noto l'i-esima colonna della matrice B. 
Utilizzarla poi per il calcolo dell'inversa delle
matrici non singolari
$$
A=\left[
\begin{array}{ccc}
3 & 5 & 7\\
2 & 3 & 4\\
5 & 9 & 11
\end{array}
\right ], \qquad
A=\left[
\begin{array}{cccc}
1 & 2 & 3 & 4\\
2 & -4 & 6 & 8\\
-1 & -2 & -3 & -1\\
5 & 7 & 0 & 1
\end{array}
\right ],
$$
confrontando i risultati ottenuti con l'output
della funzione  *scipy.linalg.inv(A)*

In [ ]:
def solve_nsis(A, B):
    m, n = A.shape
    flag = 0
    if n != m:
        print("Matrice non quadrata")
        return

    X = np.zeros((n, n))
    PT, L, U = lu(A)
    P = PT.T.copy()
    if flag == 0:
        for i in range(n):
            y, flag = functions.Lsolve(L, P @ B[:, i])
            x, flag = functions.Usolve(U, y)
            X[:, i] = x.reshape(
                n,
            )
    else:
        print("Elemento diagonale nullo")
        X = []

    return X

In [13]:
A1 = np.array([[3, 5, 7], [2, 3, 4], [5, 9, 11]])
m, n = A1.shape
B = np.eye(m)
X = solve_nsis(A1, B)
print("my inversa \n", X)
print("Inversa con linalg \n ", np.linalg.inv(A1))

A2 = np.array([[1, 2, 3, 4], [2, -4, 6, 8], [-1, -2, -3, -1], [5, 7, 0, 1]])
m, n = A2.shape
B = np.eye(m)
X = solve_nsis(A2, B)
print("my inversa \n", X)
print("Inversa con linalg \n ", np.linalg.inv(A2))

my inversa 
 [[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
Inversa con linalg 
  [[-1.5  4.  -0.5]
 [-1.  -1.   1. ]
 [ 1.5 -1.  -0.5]]
my inversa 
 [[-4.16666667e-01  1.75000000e-01 -6.66666667e-02  2.00000000e-01]
 [ 2.50000000e-01 -1.25000000e-01  6.53072367e-17 -8.16340459e-18]
 [-1.38888889e-01  2.50000000e-02 -4.22222222e-01 -6.66666667e-02]
 [ 3.33333333e-01  4.62592927e-18  3.33333333e-01 -9.25185854e-18]]
Inversa con linalg 
  [[-4.16666667e-01  1.75000000e-01 -6.66666667e-02  2.00000000e-01]
 [ 2.50000000e-01 -1.25000000e-01 -4.89804276e-17 -4.08170230e-18]
 [-1.38888889e-01  2.50000000e-02 -4.22222222e-01 -6.66666667e-02]
 [ 3.33333333e-01  3.26536184e-18  3.33333333e-01 -8.70763157e-18]]


## Esercizio 6
Sfruttando la fattorizzazione PA=LU  di una delle matrici del punto precedente, calcolarne il determinante.


In [16]:
PT, L1, U1 = lu(A2)
P = PT.copy()

det = np.prod(np.diag(U1)) * np.linalg.det(P)

print("my det: ", det)
print("Numpy det:", np.linalg.det(A2))

my det:  -359.99999999999994
Numpy det: -360.00000000000006
